# Generated by Django 5.0.7 on 2024-07-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Add_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('tel', models.CharField(max_length=20)),
                ('about_me', models.TextField(max_length=600)),
                ('my_skills', models.TextField(max_length=600)),
                ('education', models.CharField(max_length=60)),
                ('education_start_years', models.DateField(max_length=80)),
                ('education_grad_years', models.DateField(max_length=80)),
                ('speciality', models.CharField(max_length=80)),
                ('experiance_start_years', models.DateField(max_length=80)),
                ('experiance_finish_years', models.DateField(max_length=80)),
            ],
        ),
    ]
